name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        directory: 'src'
        exclusions: '*.git* /*node_modules/* .editorconfig /*resources/*'
    - uses: actions/upload-artifact@v2
      with:
        name: release.zip
        path: release.zip
    - uses: actions/download-artifact@v2
      with:
        name: release.zip